"""Named ownership and recovery contracts for every content-stopping condition."""

from __future__ import annotations

from typing import Any


TRANSFORMATIONS: tuple[dict[str, Any], ...] = (
    {
        "blocker_id": "RESEARCH_REQUIRED",
        "old_purpose": "Prevent unsupported facts.",
        "old_terminal_effect": "Knowledge gap could end the slot.",
        "owner": "KNOWLEDGE_GAP_RESOLVER",
        "inputs": ["claim_centrality", "truth_cabinet", "research_results"],
        "output": "VERIFIED_FACT_OR_CHANGED_PREMISE",
        "prevention": "Classify claim burden before writing.",
        "repair": "Verify central facts; remove supporting or incidental claims.",
        "replacement": "Change factual bridge, premise, product, or opportunity.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "UNSUPPORTED_CLAIM",
        "old_purpose": "Protect factual integrity.",
        "old_terminal_effect": "One sentence killed the post.",
        "owner": "FACT_RESOLUTION_SPECIALIST",
        "inputs": ["final_claim_set", "claim_envelope", "source_authority"],
        "output": "REPAIRED_FINAL_COPY",
        "prevention": "Writer receives a safe claim envelope.",
        "repair": "Delete, narrow, replace, question, or convert to decision guidance.",
        "replacement": "Change paragraph or premise when central.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "QUALITY_BELOW_PREFERENCE",
        "old_purpose": "Protect usefulness and craft.",
        "old_terminal_effect": "A numeric threshold produced no post.",
        "owner": "QUALITY_DOCTOR",
        "inputs": ["component_scores", "human_reality", "copy_routes"],
        "output": "REPAIR_OR_PREMISE_CHANGE",
        "prevention": "Compare multiple routes before final copy.",
        "repair": "Repair the weak dimension.",
        "replacement": "Replace a premise with multiple weak dimensions.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "DUPLICATE_OR_STALE",
        "old_purpose": "Protect audience freshness.",
        "old_terminal_effect": "Similarity exhausted a small candidate budget.",
        "owner": "FRESHNESS_NAVIGATOR",
        "inputs": ["published_memory", "human_reality", "brain_movement", "product_history"],
        "output": "FRESH_DIRECTION",
        "prevention": "Check freshness before writing.",
        "repair": "Change hook, person, job, story, or response.",
        "replacement": "Change opportunity, product, or go product-free.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "PRODUCT_FAILURE",
        "old_purpose": "Protect product fit and truth.",
        "old_terminal_effect": "A difficult product consumed the slot.",
        "owner": "PRODUCT_FIT_SPECIALIST",
        "inputs": ["eligible_products", "verified_fact_coverage", "visual_truth", "human_job"],
        "output": "CURRENT_ALTERNATE_OR_NONE",
        "prevention": "Assess product and visual feasibility in Round 0.",
        "repair": "Rotate to a better-fit product.",
        "replacement": "Set product role to NONE.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "NO_VIABLE_OPPORTUNITY",
        "old_purpose": "Avoid filler.",
        "old_terminal_effect": "A narrow search was labeled exhaustion.",
        "owner": "OPPORTUNITY_EXPANSION_SPECIALIST",
        "inputs": ["audience_moments", "brain_movements", "content_jobs", "ready_reserve"],
        "output": "EXPANDED_OPPORTUNITY_FIELD",
        "prevention": "Create a useful opportunity field before selection.",
        "repair": "Reopen person, situation, job, story, and product role.",
        "replacement": "Use a fresh reserve seed or low-claim territory.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "CANDIDATE_BUDGET_EXHAUSTED",
        "old_purpose": "Bound cost and latency.",
        "old_terminal_effect": "Attempt budget was mistaken for content exhaustion.",
        "owner": "COMPLEXITY_CONTROLLER",
        "inputs": ["attempt_diagnostics", "claim_burden", "visual_feasibility"],
        "output": "SIMPLIFIED_CONTENT_JOB",
        "prevention": "Estimate factual and creative cost in Round 0.",
        "repair": "Reduce research, story, product, or visual complexity.",
        "replacement": "Use product-free, known-fact, high-value guidance.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "VISUAL_FAILURE",
        "old_purpose": "Protect creative and product truth.",
        "old_terminal_effect": "Bad first render killed content or a packshot escaped.",
        "owner": "CREATIVE_RECOVERY_SPECIALIST",
        "inputs": ["visual_thesis", "art_direction", "product_visual_truth", "critic_result"],
        "output": "NEW_ROUTE_OR_EXTERNAL_ACTION",
        "prevention": "Assess visual feasibility and compete textual routes first.",
        "repair": "Change framing, scene, light, product role, or reference strategy.",
        "replacement": "Change route or product role; preserve copy when provider is external.",
        "may_stop_content_creation": False,
        "may_stop_external_publication": True,
        "external_reason": "No truthful final media or provider unavailable.",
    },
    {
        "blocker_id": "PLATFORM_PRESENTATION_FAILURE",
        "old_purpose": "Protect readability and native presentation.",
        "old_terminal_effect": "Formatting defect ended a complete idea.",
        "owner": "PLATFORM_EDITOR",
        "inputs": ["authoritative_copy", "platform_grammar", "destination"],
        "output": "REPAIRED_PLATFORM_COPY",
        "prevention": "Build platform packages before READY.",
        "repair": "Reorder, group, space, and resolve CTA without adding meaning.",
        "replacement": "Use semantic source to rebuild presentation.",
        "may_stop_content_creation": False,
    },
    {
        "blocker_id": "CHANNEL_OR_SCHEDULER_FAILURE",
        "old_purpose": "Protect operational correctness.",
        "old_terminal_effect": "Discovered only at publication time.",
        "owner": "OPERATIONS_READINESS_SPECIALIST",
        "inputs": ["daily_slots", "outbox", "effective_config", "publisher_auth", "clock"],
        "output": "READY_OR_EARLY_ACTION",
        "prevention": "Check readiness lead time before every slot.",
        "repair": "Rebuild inventory, restore config, or dispatch overdue content.",
        "replacement": "Classify exact owner/external action.",
        "may_stop_content_creation": False,
        "may_stop_external_publication": True,
        "external_reason": "Publisher authorization or external platform unavailable.",
    },
    {
        "blocker_id": "ARCHIVE_OR_HISTORY_FAILURE",
        "old_purpose": "Preserve learning and auditability.",
        "old_terminal_effect": "Later persistence failure could erase external success.",
        "owner": "CONTENT_LEDGER_STEWARD",
        "inputs": ["candidate_archive", "outbox", "platform_transaction"],
        "output": "RECONCILED_LEDGER",
        "prevention": "Persist intent and artifacts before irreversible calls.",
        "repair": "Reconcile receipt into aggregate history.",
        "replacement": "Rebuild read models from canonical SQLite records.",
        "may_stop_content_creation": False,
    },
)


def registry() -> list[dict[str, Any]]:
    return [dict(item) for item in TRANSFORMATIONS]


def transformation_for(reason: str) -> dict[str, Any]:
    normalized = str(reason or "").upper()
    aliases = {
        "RESEARCH": "RESEARCH_REQUIRED",
        "CLAIM": "UNSUPPORTED_CLAIM",
        "QUALITY": "QUALITY_BELOW_PREFERENCE",
        "DUPLICATE": "DUPLICATE_OR_STALE",
        "FRESH": "DUPLICATE_OR_STALE",
        "PRODUCT": "PRODUCT_FAILURE",
        "OPPORTUNITY": "NO_VIABLE_OPPORTUNITY",
        "CANDIDATE": "CANDIDATE_BUDGET_EXHAUSTED",
        "VISUAL": "VISUAL_FAILURE",
        "PRESENTATION": "PLATFORM_PRESENTATION_FAILURE",
        "CHANNEL": "CHANNEL_OR_SCHEDULER_FAILURE",
        "SCHEDULE": "CHANNEL_OR_SCHEDULER_FAILURE",
        "ARCHIVE": "ARCHIVE_OR_HISTORY_FAILURE",
        "HISTORY": "ARCHIVE_OR_HISTORY_FAILURE",
        "PERSIST": "ARCHIVE_OR_HISTORY_FAILURE",
    }
    target = next((value for key, value in aliases.items() if key in normalized), "")
    return next((dict(item) for item in TRANSFORMATIONS if item["blocker_id"] == target), {})
