const state={data:null,conversationId:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(path,options={}){const token=localStorage.getItem('infenergyToken')||prompt('Enter the Infenergy owner token');if(token)localStorage.setItem('infenergyToken',token);const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function message(role,content,status=''){const wrap=document.createElement('div');wrap.className=`message ${role} ${status}`;wrap.innerHTML=role==='assistant'?`<span class="avatar">I</span><div><strong>Infenergy Intelligence</strong><p>${esc(content)}</p></div>`:`<div><strong>Owner</strong><p>${esc(content)}</p></div>`;$('#messages').append(wrap);$('#messages').scrollTop=$('#messages').scrollHeight}
function cards(target,items){$(target).innerHTML=(items||[]).map(item=>`<div class="card"><h3>${esc(item.title||item.name||item.type||item.status||'Record')}</h3><pre>${esc(JSON.stringify(item,null,2))}</pre></div>`).join('')||'<p class="muted">No records.</p>'}
function rows(target,items,fields){$(target).innerHTML=`<div class="row head">${fields.map(f=>`<span>${esc(f)}</span>`).join('')}</div>`+(items||[]).map(item=>`<div class="row">${fields.map(f=>`<span>${esc(item[f.toLowerCase().replaceAll(' ','_')]??'—')}</span>`).join('')}</div>`).join('')}
async function load(){try{const data=await api('/api/os/state');state.data=data;state.conversationId=data.conversation?.id;render(data);$('#system-dot').className='dot ok';$('#system-label').textContent='OS connected'}catch(error){$('#system-dot').className='dot bad';$('#system-label').textContent='Connection blocked';toast(error.message)}}
function render(data){const attention=data.attention||[],jobs=data.jobs||[],policies=data.policies||[];$('#attention-count').textContent=attention.length;$('#job-count').textContent=jobs.filter(j=>!['COMPLETED','CANCELED'].includes(j.status)).length;$('#attention-list').innerHTML=attention.slice(0,4).map(x=>`<div class="list-item"><strong>${esc(x.title)}</strong><small>Score ${Number(x.score).toFixed(2)}</small></div>`).join('')||'Nothing material is waiting.';$('#job-list').innerHTML=jobs.slice(0,4).map(x=>`<div class="list-item"><strong>${esc(x.objective)}</strong><small>${esc(x.status)} · ${Math.round((x.progress||0)*100)}%</small></div>`).join('')||'No active jobs.';$('#policy-summary').innerHTML=policies.slice(0,4).map(x=>`<div class="list-item"><strong>${esc(x.capability)}</strong><small>${esc(x.approval_level)}</small></div>`).join('')||'Default deny for mutations.';const health=data.health||{};const providerCount=Object.values(health.providers||{}).filter(x=>x.configured||x.sdk_installed).length;$('#today-metrics').innerHTML=[['Attention',attention.length],['Active jobs',jobs.length],['Findings',(data.research_findings||[]).length],['Automations',(data.automations||[]).length],['Providers',providerCount]].map(([label,value])=>`<div class="metric panel"><b>${value}</b><span>${label}</span></div>`).join('');cards('#today-content',[...attention,...(data.recent_events||[]).slice(0,5)]);rows('#jobs-table',jobs,['Type','Status','Progress','Updated at']);cards('#research-content',data.research_findings||[]);cards('#automations-content',[...(data.automations||[]),...(data.watches||[])]);rows('#automation-runs',data.automation_runs||[],['Status','Started at','Finished at','Error']);cards('#health-content',[health,...Object.entries(health.providers||{}).map(([name,value])=>({name,...value}))]);cards('#permissions-content',policies);cards('#activity-table',data.recent_activity||[]);cards('#social-content',health.social_today?[health.social_today]:[]);cards('#strategy-content',policies.filter(p=>p.capability.includes('goal')||p.capability.includes('strateg')))}
$('#nav').addEventListener('click',event=>{const button=event.target.closest('button[data-view]');if(!button)return;document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(`#${button.dataset.view}`).classList.add('active');$('#view-title').textContent=button.textContent});
$('#command-form').addEventListener('submit',async event=>{event.preventDefault();const input=$('#command-input');const text=input.value.trim();if(!text)return;message('user',text);input.value='';message('assistant','Working…');const pending=$('#messages .message:last-child');try{const result=await api('/api/os/command',{method:'POST',body:JSON.stringify({message:text,conversation_id:state.conversationId})});pending.remove();message('assistant',result.message,result.status==='BLOCKED'?'blocked':'');state.conversationId=result.conversation_id;await load()}catch(error){pending.remove();message('assistant',error.message,'blocked')}});
$('#command-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('#command-form').requestSubmit()}});
$('#refresh').addEventListener('click',load);$('#new-chat').addEventListener('click',()=>{state.conversationId=null;$('#messages').innerHTML='';message('assistant','New command context started. Durable company memory remains available.')});document.addEventListener('click',async event=>{if(event.target.dataset.action==='plan120'){try{const result=await api('/api/os/execute',{method:'POST',body:JSON.stringify({capability:'content.plan_120_days',arguments:{objective:'Build the next 120 days. Entertainment first. Keep the future adaptive.'},dry_run:true})});toast(result.status);await load()}catch(error){toast(error.message)}}});load();